### ISSUE TITLE
Print fuction is being printed

### ISSUE THREAD

**Issue by awrog** [iusvar/grav-plugin-printfriendly#10]
Great plugin, dying to use it.
After adding {{ printfriendly(page.route) }} to a page of type blog (Antimatter 1.2.1) the coding associated with the print-button is being printed. Can I prevent this?
![screenshot - 11_9_2018 09_07_34](https://user-images.githubusercontent.com/12153667/48250731-902f8880-e3ff-11e8-9f97-67f45e339d4c.png)

**Comment by iusvar** [comment]
Try {{ printfriendly(page.route)|raw }}

**Comment by awrog** [comment]
Tried it, the same result.

**Comment by iusvar** [comment]
Check if twig autoescape in the system.yaml file is set off

**Comment by awrog** [comment]
Figured it out.
Unlike with other plugins, you cannot put {{ printfriendly(page.route) }} in the content of the page, it **has** to be added in the twig file.
It works now!
