### ISSUE TITLE
Twig_Error_Runtime whith v0.3.0

### ISSUE THREAD

**Issue by laurent-steamlead** [iusvar/grav-plugin-printfriendly#3]
Hi,

When the plugin is active and the 
`                   {{ printfriendly(page.route) }}
`
code is added to the template

The following error occurs :
```
Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Only variables should be passed by reference").
```

Tested with the lastest version of Grav, antimatter theme , and prettyprint.
Debug enabled

**Comment by iusvar** [comment]
Hi,
since I can not repeat the error (I also have the latest version of Grav + Antimatter) I need to see the contents of the .md file for which there is an error.

**Comment by iusvar** [comment]
I found it. It was an **explode** function within a **end** function. I fix it and put it online

**Comment by laurent-steamlead** [comment]
thanks for your reactivity, this error has gone. Well done !
But I've found another one, sorry, I post another issue for it
